const QUIZ_DATA = {
  sistemeInformaticeDeGestiune: {
    label: "Sisteme informatice de gestiune",
    questions: [
      { q: "Care dintre următoarele variante de interogare SQL va returna studenții si profesorii din provincie?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre următoarele interogări SQL are ca efect afişarea zilelor în care s-au emis mai mult de 2 chitanțe ?", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre următoarele interogări SQL permite afişarea numărului de salariaţi pentru fiecare compartiment care începe cu litera 'A'?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre următoarele interogări SQL permite afişarea numelor clienților pentru care NU au fost emise facturi în data de 1 mai 2021?", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care dintre următoarele comenzi SQL permite majorarea salariului cu 1% pentru salariaţii angajați în anul 2021?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre următoarele interogări SQL permite afişarea numărului de salariaţi pe fiecare compartiment care începe cu litera „A\"?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care este interogarea SQL ce permite afişarea tuturor profesorilor şi a denumirii facultăților la care predau aceştia, ordonați alfabetic după denumirea facultăților ?", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care este interogarea SQL care afişează numele salariaţilor care câștiga mai mult decât salariul mediu pe companie, în ordine crescătoare a salariului?", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care este interogarea SQL ce afişează toate funcțiile pentru care nu există angajaţi?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care definiție este corectă:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Sistemul informaţional cuprinde:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Sunt componente principale ale unui sistem informatic:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Sunt structuri de control fundamentale în realizarea programelor:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Ciclul prelucrării datelor pentru sistemul informatic cuprinde următoarele faze:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Metodologiile de realizare a sistemelor informatice cuprind:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care din afirmaţiile următoare sunt corecte:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Nu este faza a ciclului de viaţă al dezvoltării sistemelor:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Sistemul de Gestiune a Bazelor de Date este:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Diagramele Gantt se utilizează pentru:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Studiul sistemului existent constă în:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Metodele tradiţionale de determinare a cerinţelor sistemelor sunt:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Scopul diagramelor de date DFD este de a scoate în relief, într-o manieră cât mai sugestivă, următoarele aspecte:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Simbolul folosit în diagramele DFD realizate cu SSADM, pentru reprezentarea fluxului de date sunt:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Raportul detaliat al cerinţelor sistemului conţine următoarele elemente:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Principalele elemente ale documentației elaborate pentru modelarea logicii proceselor sunt:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Cea mai cunoscută formă utilizată pentru modelarea conceptuală a datelor este:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "În DER pentru fiecare entitate reprezentată se apelează la simbolul:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care din afirmaţiile următoare nu sunt corecte:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Prezentarea informaţiile din formulare/formate şi rapoarte pot fi oferite:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Alegerea tipului de suport fizic de ieşire (imprimantă, display, etc.) se face în funcţie de:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Macheta documentului de intrare conţine:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre următoarele interogări SQL are ca efect afişarea unei liste cu produsele care au fost achiziționate în cantități cuprinse între 50 și 100, sortate alfabetic, după denumire ?", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre urmatoarele interogari SQL are ca efect afisarea unei liste cu produsele care sunt din categoria \"papetarie\" si au fost achizitoinate in cantitati mai mari de 50:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care dintre următoarele interogări SQL are ca efect afişarea zilelor în care s-au emis mai mult de 2 chitanțe:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre urmatoarele instructiuni SQL permite afisarea numarului de salariati pe fiecare compartiment care incepe cu litera „A\":", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre urmatoarele interogari SQL permite afisarea numelui si a functiei angajatilor cu o vechime mai mare de 5 ani:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre urmatoarele interogari SQL permite afisarea numelor clientilor pentru care nu au fost emise facturi in data de 10 ianuarie 2021:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care dintre urmatoarele interogari SQL are ca efect afisarea unei liste cu denumirea furnizorilor de la care s-au achizitionat produse a caror valoare TVA din pretul unitar nu depaseste 100 lei", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre urmatoarele interogari SQL permite calculul sumei totale facturate pe fiecare oras in luna iulie 2021:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre urmatoarele interogari SQL are ca efect stergerea clientilor care au cumparat produse in ultima saptamana:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre urmatoarele interogari SQL are ca efect micsorarea cu 10% a sumelor de pe chitantele eliberate la ghiseul numarul 3 în anul 2021:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre urmatoarele interogari SQL are ca efect afisarea unei liste cu denumirea clientului si denumirea produsului pentru produsele vandute in anul curent:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre urmatoarele interogari SQL permite stergerea numarului de telefon pentru clientii din afara Sibiului:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre urmatoarele interogari SQL are ca efect afisarea unei liste cu denumirea clientului, denumirea produsului, cantitatea, pretul, tva si valoarea totala, pentru produsul „ара\":", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre urmatoarele instructiuni SQL permite stergerea salariatilor angajati înainte de începutul anului 2020 cu profesia \"economist\":", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care dintre urmatoarele instructiuni SQL permite majorarea salariului cu 1% pentru salariatii angajati în anul 2020:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre următoarele interogări SQL are ca efect afişarea valorii totale din fiecare lună a anului curent:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre următoarele interogări SQL are ca efect calcularea TVA, pe coloana tva, pentru înregistrările realizate în anul curent:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care este rezultatul interogarii: SELECT denumire FROM produse WHERE data_fab data_exp = 30 OR producator = „SC X SRL\" AND data_exp=Date()", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care este rezultatul interogării: SELECT Nume, Telefon FROM Clienti WHERE Clienti. CodCL IN (SELECT CodCL FROM Facturi WHERE DataFact =Date() AND Valoare >500) AND Oras<>\"Sibiu\"", o: ["A", "B", "C", "D"], a: 2 }
    ]
  },
  microeconomie: {
    label: "Microeconomie",
    questions: [
      { q: "Presupunem că prețul unui bun scade cu 10%, iar cantitatea cerută pentru o anumită perioadă de timp crește cu 15%. În aceste condiții:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "O creştere a preţului cu 50% antrenează o creştere a cantităţii oferite dintr-un bun economic de la 10 la 20 bucăţi. Să se calculeze coeficientul de elasticitate al ofertei:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Alegeți afirmaţia falsă:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Alegeți răspunsul corect dintre variantele A, B, C, D:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Pentru un consumator, utilitatea marginală a untului este reprezentată de funcţia Umgu= 40 - 5Qu, iar utilitatea marginală a pâinii de funcţia Umgp=20-3Qp, preţul untului Pu=5, preţul pâinii Pp=1 Venitul disponibil pentru a cumpăra aceste bunuri este 20 u.m. Calculaţi cantităţile de unt si pâine consumate în echilibru de către consumatorul dat.", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Utilitatea totală coincide cu cea marginală:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Potrivit legii utilităţii marginale:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Curba de indiferenţă semnifică:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Consumatorul dispune de un venit de 80 u.m., cheltuindu-l pe cumpărarea a 2 bunuri: bunul x la preţul de 5 u.m. şi bunul y la preţul de 4 u.m. Care combinaţie din cele indicate este inaccesibilă?", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Consumatorul dispune de un venit de 8 u.m. Preţul bunului X este de 1 u.m., preţul bunului Y 0,5 u.m. Care dintre următoarele combinaţii se află pe linia bugetului?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Punctele la intersecţia liniei bugetului cu axele coordonatelor semnifică:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Când cantitatea consumată dintr-un bun creşte, utilitatea marginală pe care o aduce fiecare nouă doză consumată:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Funcţia cererii pentru telefoanele mobile este Q=200-P iar pentru oferta Q=20+P (unde Q reprezintă cantitatea şi p reprezintă preţul). La ce nivel al preţului se va constata un exces de cerere pe piaţa telefoanelor mobile?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Presupunem că oferta pentru produsul A este perfect elastică. Dacă cererea pentru acest produs creşte:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "În condiţiile în care coeficientul elasticităţii cererii în funcţie de venit este mai mare decât 1 şi venitul creşte, ponderea cheltuielilor pentru marfa X în cheltuielile totale:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Fie funcţia ofertei P=3+2Qo şi funcţia cererii P=9-Qc", o: ["A", "B", "C", "D"], a: 0 },
      { q: "În situaţia în care cererea pentru produsele agricole este inelastică:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Pentru un consumator rațional care are de ales între două bunuri în condițiile constrângerii bugetare, modificarea prețului unuia dintre bunuri, caeteris paribus, va determina:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care dintre factorii de mai jos determină creşterea sau scăderea cantităţii cerute la acelaşi nivel al preţului (alegeţi varianta corectă):", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Preţul produsului A s-a redus de la 100 la 90 lei şi, ca urmare, cantitatea cerută a crescut de la 70 la 75 unităţi. Cererea este:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "În situaţia în care costul fix mediu în perioada 0 al unei firme este 30.000 lei. La un spor al producţiei de 50%, costul fix mediu în perioada 1 devine:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Efectul de substituire constă în:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Un agent economic depune la o bancă o sumă de 10.000 lei cu o rată a dobânzii de 5%. Care va fi suma existentă în bancă după 2 ani dacă agentul economic nu execută retrageri din contul creat în această perioadă?:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "În cazul în care curba cererii pentru produsul A se deplasează la dreapta, iar preţul pentru produsul B scade, se poate concluziona că:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Preţul unui bun este de 400 u.m., iar cantitatea cerută din acel bun este de 1000 bucăţi. La un moment ulterior previziunile pieţei privind scăderea preţului bunului respectiv se îndeplinesc, astfel preţul va fi de 360 u.m. Care ar fi reacţia cantităţii cerute pentru a ne regăsi în situaţia unui bun cu cerere inelastică?", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Capitalul circulant:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care din următoarele aspecte delimitează capitalul fix de cel circulant:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Capitalul tehnic consumat este egal cu:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Valoarea capitalului utilizat într-o firmă este de 30.000 u.m. din care 16.000 u.m. reprezintă capital circulant. Capitalul consumat fiind de 20.000 u.m., valoarea capitalului neamortizat după un an este:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "La o societate comercială se dau următoarele date: costuri materiale 89 mil.; capital circulant 45 mil.; salarii indirecte 10 mil.; costuri fixe 90 mil.; costuri variabile 52 mil. Să se calculeze costurile materiale fixe şi amortizarea:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Fiind dată relaţia CTM=20Q (CTM - costul total mediu, Q producţia), costul marginal al celei de-a cincea unităţi de producţie este:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "În componenţa costului fix se includ:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Într-o firmă producţia înregistrată scade cu 40%. Cum se modifică CFM?", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Când volumul producţiei este zero:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Să se calculeze CFM, pentru un nivel al producţiei Q=20, ştiind că funcţia costului total este: CT=200+3Q+2Q^2", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre următoarele afirmaţii este falsă:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Pe piaţa cu concurenţă perfectă:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre condiţiile următoare indică faptul că un bun este produs în condiţii de concurenţă perfectă:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Curba cererii pe o piaţă cu concurenţă monopolistică este:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Condiţia de maximizare a profitului în cazul unei firme pe o piaţă cu concurenţă monopolistică este următoarea Vmg este venitul marginal, Cmg costul marginal, P este preţul, CTM costul mediu, VT veniturile totale):", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre următoarele afirmaţii cu privire la monopol sunt adevărate:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Între concurenţa monopolistică şi cea perfectă există diferenţe privind:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Să presupunem că o firmă are funcţie a costului total de forma CT(Q)=125+4Q^2. Determinaţi cantitatea şi preţul care maximizează profitul total dacă firma acţionează pe o piaţă de monopol şi funcţia cererii este P=100-Q", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre următoarele pot fi considerate trăsăturile de bază ale bunurilor publice:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care dintre următoarele soluţii nu fac parte dintre căile de internalizare a externalităţilor:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care dintre următorii economişti a afirmat că problema externalităţilor poate fi rezolvată, în anumite condiţii, fără intervenţie guvernamentală:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Dacă o activitate economică se concretizează în producerea a două bunuri, unul ce generează externalităţi pozitive şi altul care generează externalităţi negative, consecinţele pe piaţă vor fi următoarele:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Următorul tabel evidențiază posibilitățile producerii a două bunuri - telefoane și calculatoare. Care este costul de oportunitate (în unități monetare) al unui telefon prin mişcarea de la B la C, dacă prețul unui calculator este de 280 euro?", o: ["A", "B", "C", "D"], a: 2 },
      { q: "În mod normal, economia naturală se caracterizează prin:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care dintre trăsăturile de mai jos definesc trebuințele umane:", o: ["A", "B", "C", "D"], a: 3 }
    ]
  },
  contabilitateFinanciara: {
    label: "Contabilitate financiară",
    questions: [
      { q: "Înregistrarea contabilă 462 = % (7583 şi 4427) semnifică:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Ce reprezintă înregistrarea contabilă 1012=456 10.000", o: ["A", "B", "C", "D"], a: 2 },
      { q: "După funcţiunea contabilă, contul 2672 \"Dobânda aferentă sumelor de încasat de la entităţile afiliate\" este:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Contabilitatea trezoreriei trebuie organizată şi condusă în aşa fel încât să asigure înfăptuirea următoarelor obiective:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "O imobilizare corporală care este recunoscută ca un activ, la intrarea în gestiune, se evaluează:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "În toate situaţiile, cheltuielile ulterioare aferente unui activ recunoscut ca o imobilizare necorporală:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Rezerva legală maximă deductibilă fiscal care se poate constitui în exerciţiul financiar curent este de:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care este valoarea contabilă a unei acţiuni înainte şi după majorarea capitalului, mărimea teoretică a DS-ului şi raportul de paritate între vechile şi noile acţiuni?", o: ["A", "B", "C", "D"], a: 0 },
      { q: "În funcţie de natura relaţiilor ce apar între entitatea economică şi acţionari/asociaţi se disting:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Contul 609 \" Reduceri comerciale primite\" funcţionează ca şi un cont:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Valoarea cheltuielilor de dezvoltare finalizate şi recepţionate, efectuate în regie proprie, se înregistrează prin formula contabilă:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care este suma care se va înscrie în bilant la postul „Datorii ce trebuie plătite într-o perioadă mai mică de 1 an\"", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Indicaţi înregistrările contabile corecte privind cedarea către un terţ a unei construcţii incomplet amortizate, preţ vânzare negociat 50.000 lei, TVA 21%. Valoarea contabilă a construcţiei este de 30.000 lei iar suma amortizării la data cedării este de 20.000 lei.", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Se acordă administratorului un avans de trezorerie în sumă de 2.000 lei. Ulterior, avansul se decontează astfel: 400 lei pentru transportul personal şi 500 lei pentru acţiuni de protocol. Suma neconsumată se depune la casierie. Completaţi formula contabilă privind justificarea avansului de trezorerie :", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Înregistrarea în contabilitate a dreptului entităţii economice deţinătoare de acţiuni, de a încasa dividende în sumă de 10.000 lei de la alte entităţi din cadrul grupului, se realizează prin următoarea formulă contabilă:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "\"ALFA\" S.A. scoate din folosinţă materiale de natura obiectelor de inventar în valoare de 2.500 lei. Înregistrarea contabilă va fi următoarea :", o: ["A", "B", "C", "D"], a: 3 },
      { q: "În cursul lunii sunt recepţionate semifabricate la preţ prestabilit de 88.500 lei. Costul efectiv al semifabricatelor, determinat la finele lunii este de 90.050 lei. Înregistrarea contabilă privind diferenţele de preţ aferente semifabricatelor obţinute va fi următoarea:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "O societate primeşte cu titlu gratuit mărfuri, evaluate la 3.000 lei. Să se completeze formula contabilă:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "O societate care are ca obiect de fabricarea de autocamioane dispune ca, din stocul de produse finite, să fie reţinut un autocamion pentru nevoile proprii ale întreprinderii. Costul de producţie al unui autocamion este de 35.000 lei. Care sunt înregistrările contabile care se impun în această situaţie:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Se obţin în cursul lunii din producţie proprie produse finite evaluate la preţ prestabilit (standard), în valoare de 23.000 lei. La finele lunii, din contabilitatea de gestiune rezultă un cost de producţie efectiv de 25.000 lei. Înregistrarea în contabilitate a produselor finite obţinute în cursul lunii, se realizează astfel:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Societatea constituie ajustări pentru deprecierea materiilor prime în valoare de 5.000 lei. Să se completeze formula contabilă:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "O societate demarează la 01.01.N lucrările pentru construcţia unei clădiri în regie proprie. Clădirea va fi dată în funcţiune la data de 01.10.N+1 iar cheltuielile efectuate pe parcursul celor două exerciţii sunt: În exerciţiul N: consum de materiale consumabile 100.000 lei, amortizarea utilajelor folosite pentru construcţii 50.000 lei, taxe nerecuperabile 5.000 lei, taxe recuperabile aferente cumpărărilor de materii prime 20.000 lei; În exerciţiul N+1 consum de materiale consumabile 20.000 lei, amortizarea utilajelor folosite pentru construcţii 40.000 lei, salarii directe 80.000 lei, taxe nerecuperabile 10.000 lei. Înregistrarea recepţiei clădirii la data de 01.10.N+1 se face prin formula contabilă:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Ce semnifică următoarea formulă contabilă: 601 = 301 2.000 lei", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Accizele şi taxele vamale aferente materiilor prime importate din spaţiul extracomunitar în valoare de 10.000 lei, se înregistrează în contabilitate astfel:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care este formula contabilă pentru înregistrarea amortizării concesiunilor în rate lunare, pe mai multe perioade :", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Se constată la inventariere un plus de produse finite la preţ de înregistrare de 4.000 lei. Completaţi formula contabilă:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Preţul de vânzare cu amănuntul al mărfurilor (PAM) se determină astfel:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Contabilizarea stocurilor conform metodei inventarului permanent, presupune:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Societatea \"ALFA\" S.A. a achiziţionat de la un furnizor materii prime, cost achiziţie 30.000 lei (inclusiv TVA de 21%). Înregistrarea stingerii obligaţiei de plată faţă de furnizor, printr-un efect comercial, se realizează prin următoarea formulă contabilă:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Care este formula contabilă pentru evidenţierea cheltuielilor cu primele de asigurare datorate, conform contractului de asigurare, în valoare de 1.000 lei?", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Se vând produse finite unui client, conform facturii, la preţ de vânzare negociat de 12.000 lei, TVA 21%. Clientul subscrie un bilet la ordin. Completaţi formula contabilă de încasare la scadenţă a biletului la ordin şi de stingere a creanţei generată de acesta.", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Completaţi formula contabilă privind evidenţa cheltuielilor anticipate achitate în numerar în sumă de 5.000 lei și care urmează a se suporta eşalonat pe cheltuieli, pe baza unui scadenţar, în perioadele viitoare:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Firma înregistrează o creanţă faţă de un client în sumă de 25.000 lei (din care TVA 21%). Clientul este declarat în stare de faliment, probabilitatea de neîncasare a creanţei fiind de 60%. Care sunt operaţiile contabile şi sumele corecte aferente lor:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Repartizarea profitului net din exerciţii precedente pentru constituirea altor rezerve în sumă de 30.000 lei, se înregistrează în contabilitate prin formula contabilă:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Dispuneți de următoarele date din contabilitatea curentă: venituri totale 6.000 lei, din care venituri din anularea provizioanelor deductibile fiscal 1.500 lei și venituri din dividend cuvenite 500 lei. Cheltuielile totale însumează 2.000 lei, din care amenzi datorate autorităților române 1.800 lei. Determinați suma impozitului pe profit datorat (cota 16%).", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Evidenţa contabilă a reţetelor, formulelor, modelelor şi proiectelor achiziţionate se ţine cu ajutorul contului:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care este formula contabilă ce reflectă înregistrarea amortizării primelor privind rambursarea obligaţiunilor în sumă de 20.000 lei:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "A fost luată în evidenţă o datorie de 13.000 USD faţă de un furnizor extern, la cursul de 4,10 lei/USD. Datoria a fost achitată ulterior la cursul de 4,22 lei/USD. Care este formula contabilă privind reflectarea plăţii:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Alegeți formula contabilă corectă privind înregistrarea în contabilitate a avizului de însoțire a mărfurilor primit de la furnizor, în sumă de 10.000 lei, TVA 21%:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Se încasează în numerar contravaloarea chiriei pentru un imobil, în valoare de 2.000 lei. Completaţi formula contabilă:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Entitatea economică ține evidența stocurilor de mărfuri la preț de vânzare cu amănuntul inclusiv TVA și practică un adaos comercial de 30%. Se aprovizionează cu mărfuri de la furnizori, pe baza facturii fiscale: preț cumpărare exclusiv TVA 9.500 lei, cheltuieli transport înscrise în factură 500 lei, TVA 21%. Prețul de vânzare cu amănuntul al mărfurilor este:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Precizaţi semnificaţia următoarei înregistrări contabile : 161 = 765 20.000", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Ce semnificaţie are formula contabilă:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care este semnificaţia formulei contabile: 6581 = 4481 3.000", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care este formula contabilă privind înregistrarea dobânzilor de încasat, aferente împrumuturilor acordate de entitatea economică, pe termen lung, entităţilor afiliate, în sumă de 5.000 lei:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Vânzarea unei imobilizări corporale de către întreprindere reprezintă o operaţiune de natură:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Ce semnifică următoarea formulă contabilă: 104 = 106 5.000", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care este formula contabilă privind înregistrarea dobânzilor datorate de entitate, aferente împrumuturilor şi datoriilor asimilate, în sumă de 7.000 lei?", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Completaţi formula contabilă privind înregistrarea încasării înainte de termen a unei creanţe de 5.000 lei, pentru care se acordă un scont de 10%:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Se livrează produse finite unui client, conform facturii, la preţ de vânzare negociat de 10.000 lei, TVA 21%. Costul efectiv al produselor finite livrate este de 8.500 lei. Care sunt înregistrările corecte:", o: ["A", "B", "C", "D"], a: 3 }
    ]
  },
  bazeleContabilitatii: {
    label: "Bazele contabilității",
    questions: [
      { q: "Procedeele specifice metodei contabilității sunt următoarele:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Procedeele comune tuturor științelor folosite de metoda contabilității sunt următoarele:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Identificați ecuația de echilibru corectă:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Caracteristicile activelor imobilizate sunt:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Caracteristicile activelor circulante sunt:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Care principiu al contabilității presupune că la evaluarea activelor și pasivelor, cheltuielilor și veniturilor, trebuie să se ţină seama de deprecierile, riscurile şi pierderile posibile generate de desfăşurarea activității exercițiului curent sau anterior:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Care principiu al contabilității presupune ca situațiile financiare să evidențieze toate operațiile economice și financiare, precum și informațiile a căror importanță poate afecta evaluările și deciziile:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Capitalul propriu al entității reprezintă:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Distincţia dintre un activ patrimonial și o cheltuială constă în faptul că:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "La ieşirea din gestiune, stocurile fungibile pot fi evaluate utilizându-se:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Determinați valoarea stocului final al contului 301 „Materii prime\" pentru luna iulie, utilizând metoda primului intrat primul ieşit (FIFO), cunoscând următoarele mişcări:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Determinați valoarea stocului final al contului 301 „Materii prime\" pentru luna iunie, prin metoda costului mediu ponderat calculat la finalul lunii, cunoscând următoarele:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "În categoria conturilor de cheltuieli nu se includ:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "În categoria capitalurilor proprii nu se includ:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Identificați elementul care nu face parte din categoria capitalurilor proprii:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "În categoria creanţelor nu se includ:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Ordonați următoarele elemente de activ în ordinea crescătoare a lichidității:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Pentru a se păstra egalitatea bilanțieră, atunci când valoarea unei datorii scade trebuie ca:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Identificați tipul de modificare bilanțieră atrasă de operațiunea de încasare a unei creanţe faţă de un client:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Identificați tipul de modificare bilanțieră atrasă de operațiunea de achiziție a unui mijloc de transport de la furnizorul de imobilizări:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Identificați tipul de modificare bilanțieră atrasă de operațiunea de vânzare produse finite către clienți, încasarea realizându-se ulterior:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Identificați operațiunea care determină o modificare bilanțieră de tipul A+X=P+X", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Identificați operațiunea care determină o modificare bilanțieră de tipul A-X=P-X", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Identificați operațiunea care determină o modificare bilanțieră de tipul A=P+X-X", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Procesul de constituire a unei entități economice, presupune înregistrarea în contabilitate a:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Identificați afirmaţia corectă privitoare la amortizarea activelor imobilizate:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "O entitate economică a achiziționat la data de 10.12.N un echipament tehnologic în valoare de 36.000 lei, pus în funcțiune în aceeași lună, pentru care durata normată de funcționare a fost stabilită la 4 ani. Determinați valoarea amortizării anuale pentru anul N+3, ştiind că entitatea utilizează regimul accelerat de amortizare.", o: ["A", "B", "C", "D"], a: 3 },
      { q: "O entitate economică a achiziționat în 10.12.N un utilaj în valoare de 14.400 lei, pus în funcțiune în aceeași lună, pentru care durata normată de funcționare a fost stabilită la 4 ani. Determinați valoarea rămasă de amortizat la data de 31.12.N+2, ştiind că entitatea utilizează regimul accelerat de amortizare.", o: ["A", "B", "C", "D"], a: 1 },
      { q: "La finalul exercițiului financiar, o entitate prezintă următoarele elemente patrimoniale: ... Identificați valoarea capitalurilor permanente.", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Determinați valoarea activului bilanțier al unei entități, cunoscând următoarele: ...", o: ["A", "B", "C", "D"], a: 1 },
      { q: "La finalul perioadei contabile, conturile bifuncționale:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Dubla înregistrare (sau înregistrarea „în partidă dublă\") presupune:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Ce reprezintă următoarea formulă contabilă? 104 = 106 2.000 lei", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Determinați valoarea de intrare a unui utilaj, cunoscând următoarele: ...", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Soldul final al unui cont de pasiv se determină ca:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Soldul final al unui cont de activ se determină ca:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Determinați soldul final al contului 2133 „Mijloace de transport\", cunoscând următoarele: ...", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Ce reprezintă următoarea formulă contabilă? 6811=2813 2.000 lei", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre următoarele conturi reflectă o datorie financiară (pe termen lung) a entității:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Care dintre următoarele conturi reflectă creanţe ale entității:", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Identificați formula contabilă corectă pentru operațiunea de încasare în numerar a unei creanţe de 10.000 lei faţă de un client:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Identificați formula contabilă corectă pentru operațiunea de vânzare (livrare) mărfuri către clienți pe baza facturii 10.000 lei plus TVA 21%, cu încasarea ulterioară, la data scadenței:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "În luna ianuarie se vând unui client mărfuri în valoare de 12.100 lei, TVA 21% inclusă, cu încasarea la scadența convenită de 30 de zile. Completați adecvat formula contabilă de vânzare:", o: ["A", "B", "C", "D"], a: 2 },
      { q: "În luna ianuarie se cumpără de la un furnizor materii prime în valoare de 5.000 lei, plus TVA 21%, cu plata la scadența convenită de 30 de zile. Completați adecvat formula contabilă de achiziţie:", o: ["A", "B", "C", "D"], a: 1 },
      { q: "Se înregistrează amortizarea lunară, în regim liniar a unui program informatic a cărui valoare de intrare este 7.200 lei, iar durata normată de funcționare 3 ani. Completați adecvat formula contabilă de amortizare:", o: ["A", "B", "C", "D"], a: 3 },
      { q: "Ce reprezintă următoarea formulă contabilă? 711=345 10.000 lei", o: ["A", "B", "C", "D"], a: 2 },
      { q: "Identificați operațiunea care determină o modificare bilanțieră de tipul A-X=P-X", o: ["A", "B", "C", "D"], a: 1 },
      { q: "La finalul exercițiului financiar, o entitate prezintă următoarele elemente patrimoniale: ... Identificați valoarea activelor circulante.", o: ["A", "B", "C", "D"], a: 2 },
      { q: "O societate a achiziționat la data de 15.10.N un echipament tehnologic în valoare de 72.000 lei, pus în funcțiune în aceeași lună, pentru care durata normală de funcționare a fost stabilită la 4 ani. Determinați valoarea amortizării anuale pentru anul N+3, ştiind că entitatea utilizează regimul accelerat de amortizare.", o: ["A", "B", "C", "D"], a: 0 },
      { q: "Determinați valoarea pasivului bilanțier al unei entități, cunoscând următoarele: ...", o: ["A", "B", "C", "D"], a: 2 }
    ]
  }
};